export default [
    {
      id: 101,
      category: 'Beverages',
      name: 'Diet Coke',
      image: require('../assets/main/dietcoke.png'),
      price: 1.99,
      description: 'Diet Coke 325ml',
    },
    {
      id: 102,
      category: 'Beverages',
      name: 'Sprite Can',
      image: require('../assets/main/sprite.png'),
      price: 1.5,
      description: 'Sprite Can 325ml',
    },
    {
      id: 103,
      category: 'Beverages',
      name: 'Apple & Grape Juice',
      image: require('../assets/main/applegrape.png'),
      price: 15.99,
      description: '2L Apple & Grape Juice',
    },
    {
      id: 104,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 105,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 106,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 107,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 108,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 109,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 1010,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 111,
      name: 'Organic Bananas',
      category: 'Fresh Fruits & Vegetable',
      price: 4.99,
      image: require('../assets/main/home/tao.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 112,
      name: 'Red Apple',
      category: 'Fresh Fruits & Vegetable',
      price: 4.99,
      image: require('../assets/main/home/tao.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 113,
      name: 'Peper',
      category: 'Beverages',
      price: 4.99,
      image: require('../assets/main/home/ot.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 114,
      name: 'Ginger',
      category: 'Beverages',
      price: 4.99,
      image: require('../assets/main/home/gung.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 115,
      name: 'Beef Bone',
      category: 'Meat & Fish',
      price: 4.99,
      image: require('../assets/main/home/lon.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 116,
      name: 'Broiler Chicken',
      category: 'Meat & Fish',
      price: 4.99,
      image: require('../assets/main/home/ga.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 117,
      name: 'Dal Masoor',
      category: 'Meat & Fish',
      price: 2.99,
      image: require('../assets/main/home/dal.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 118,
      name: 'Rice Premium',
      category: 'Fresh Fruits & Vegetable',
      price: 3.99,
      image: require('../assets/main/home/rice.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 119,
      name: 'Egg Chicken White',
      category: 'Dairy & Eggs',
      price: 4.99,
      image: require('../assets/main/home/egg2.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 120,
      name: 'Egg Chicken Red',
      category: 'Dairy & Eggs',
      price: 500,
      image: require('../assets/main/home/egg1.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 121,
      name: 'Egg Noodle',
      category: 'Dairy & Eggs',
      price: 3.78,
      image: require('../assets/main/home/noodle.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 122,
      name: 'Egg Pasta',
      category: 'Dairy & Eggs',
      price: 2.09,
      image: require('../assets/main/home/pasta.png'),
      description: '325ml Coca Cola Can',
    },
    {
      id: 123,
      name: 'Mayonnaise Eggiess',
      category: 'Dairy & Eggs',
      price: 50,
      image: require('../assets/main/home/mayo.png'),
      description: '325ml Coca Cola Can',
    },
    
  ];
  