export default [
    {
      id: 101,
      category: 'Beverages',
      name: 'Diet Coke',
      image: require('../assets/main/dietcoke.png'),
      price: 1.99,
      description: 'Diet Coke 325ml',
    },
    {
      id: 102,
      category: 'Beverages',
      name: 'Sprite Can',
      image: require('../assets/main/sprite.png'),
      price: 1.5,
      description: 'Sprite Can 325ml',
    },
    {
      id: 103,
      category: 'Beverages',
      name: 'Apple & Grape Juice',
      image: require('../assets/main/applegrape.png'),
      price: 15.99,
      description: '2L Apple & Grape Juice',
    },
    {
      id: 104,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 105,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 106,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 107,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 108,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 109,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
    {
      id: 1010,
      category: 'Beverages',
      name: 'Coca Cola Can',
      image: require('../assets/main/coke.png'),
      price: 4.99,
      description: '325ml Coca Cola Can',
    },
  ];
  